### ISSUE TITLE
Self Driving Car: .7z files won't work properly on the model

### ISSUE THREAD

**Issue by vagman** [nicknochnack/ReinforcementLearningCourse#2]
Unless I'm missing something on the [tutorial](https://www.youtube.com/watchv=Mut_u40Sqz4&ab_channel=NicholasRenotte), .7z files for the self-driving car won't work. I get the following Erro message:
```
Traceback (most recent call last):
  File "/Users/vagman/Desktop/uni-classes/self-driving-car/car.py", line 38, in <module>
    model = PPO.load(ppo_path, env)
  File "/opt/homebrew/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 709, in load
    if "policy_kwargs" in data:
TypeError: argument of type 'NoneType' is not iterable
```
```python
# 1. Import libraries
import os
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env.dummy_vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

# 2. Test Environment
environment_name = "CarRacing-v0"
env = gym.make(environment_name)
episodes = 1

for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score+=reward
    print('Episode: {} - Score:{}'.format(episode, str(score)[:6]))
env.close()

# 3. Train Model
print("Training our model..")
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])
log_path = os.path.join('Training', 'Logs')
model = PPO("CnnPolicy", env, verbose = 1, tensorboard_log = log_path)
model.learn(total_timesteps = 2000000)

# 4. Save/Load Model
print("Saving the model to a file..")
ppo_path = os.path.join('Training', 'Saved Models', 'PPO_2m_Driving_model_2')
model = PPO.load(ppo_path, env)

# 5 Evaluate and Test
print("Evaluating our model..")
evaluate_policy(model, env, n_eval_episodes = 10, render = True)
```
I tried to convert the .7z training file into .zip. The program will run normally but the car won't move at all when I add `PPO_2m_Driving_model_2.zip` in load(). The car will keep losing points and it will restart the map once again repeating the same process.
Any ideas ?

**Comment by istteak** [comment]
You don't need to convert `PPO_2m_Driving_model_2.7z` into `PPO_2m_Driving_model_2.zip`. Because that is not training model.

You need to extract that `PPO_2m_Driving_model_2.7z` folder using [7-Zip](https://www.7-zip.org/) or [WinRAR](https://www.win-rar.com/start.html?&L=0).

After extracting that `PPO_2m_Driving_model_2.7z` folder, you will get `PPO_2m_Driving_model_2` folder. Open that folder, you will find a `.zip` folder named `PPO_2m_Driving_model_2.zip` which is the trained model. Use that folder to load the model.

I hope it will solve the problem.

**Comment by ghost** [comment]
**Did you try to convert that `.7z` into `.zip` manually(by renaming)?**

If "Yes" then you don't need to convert `PPO_2m_Driving_model_2.7z` into `PPO_2m_Driving_model_2.zip`. Because that is not the trained model.

You need to extract that `PPO_2m_Driving_model_2.7z` folder using [7-Zip](https://www.7-zip.org/) or [WinRAR](https://www.win-rar.com/start.html?&L=0).

After extracting that `PPO_2m_Driving_model_2.7z` folder, you will get `PPO_2m_Driving_model_2` folder. Open that folder, you will find a `.zip` folder named `PPO_2m_Driving_model_2.zip` which is the trained model. Use that folder to load the model.

---

And I think if you are loading a previously trained model, you don't need to train again. You can do just:

1. Import dependencies
2. Create an environment and vectorized that
3. Set the model path
4. Load the model
5. Evaluate and test

```python
import os
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

environment_name = "CarRacing-v0"
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])

ppo_path = os.path.join("Training", "Saved Models", "PPO_428k_Driving_model")
model = PPO.load(ppo_path, env)

evaluate_policy(model, env, n_eval_episodes=10, render=True)

```
---

I hope it will solve the problem.

---
